create table if not exists public.daily_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  game_id text not null,
  date_key text not null,
  seed integer not null,
  score integer not null default 0 check (score >= 0),
  replay_code text,
  summary_json jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, game_id, date_key)
);

create index if not exists daily_scores_game_date_score_idx
  on public.daily_scores (game_id, date_key, score desc, created_at asc);

create index if not exists daily_scores_user_game_date_idx
  on public.daily_scores (user_id, game_id, date_key);

alter table public.daily_scores enable row level security;

drop trigger if exists daily_scores_set_updated_at on public.daily_scores;
create trigger daily_scores_set_updated_at
before update on public.daily_scores
for each row
execute function public.set_updated_at();

drop policy if exists daily_scores_select_own on public.daily_scores;
create policy daily_scores_select_own
on public.daily_scores
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists daily_scores_insert_own on public.daily_scores;
create policy daily_scores_insert_own
on public.daily_scores
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists daily_scores_update_own on public.daily_scores;
create policy daily_scores_update_own
on public.daily_scores
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists daily_scores_delete_own on public.daily_scores;
create policy daily_scores_delete_own
on public.daily_scores
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.get_daily_challenge_seed(
  p_game_id text,
  p_date_key text
)
returns integer
language sql
immutable
as $$
  select (
    (('x' || substr(md5(coalesce(p_game_id, '') || ':' || coalesce(p_date_key, '')), 1, 7))::bit(28)::int)
    % 1000000
  )::integer;
$$;

create or replace function public.get_daily_challenge(p_game_id text)
returns table (
  date_key text,
  seed integer,
  has_used_official_attempt boolean,
  my_score integer
)
language sql
stable
security definer
set search_path = public
as $$
  with current_day as (
    select to_char(timezone('Asia/Seoul', now()), 'YYYY-MM-DD') as date_key
  ),
  my_entry as (
    select ds.score
    from public.daily_scores ds
    cross join current_day cd
    where ds.user_id = auth.uid()
      and ds.game_id = p_game_id
      and ds.date_key = cd.date_key
    limit 1
  )
  select
    cd.date_key,
    public.get_daily_challenge_seed(p_game_id, cd.date_key) as seed,
    exists(select 1 from my_entry) as has_used_official_attempt,
    (select score from my_entry limit 1) as my_score
  from current_day cd;
$$;

create or replace function public.submit_daily_score(
  p_game_id text,
  p_date_key text,
  p_seed integer,
  p_score integer,
  p_replay_code text default null,
  p_summary_json text default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_current_date_key text := to_char(timezone('Asia/Seoul', now()), 'YYYY-MM-DD');
  v_expected_seed integer := public.get_daily_challenge_seed(p_game_id, p_date_key);
  v_inserted_score integer;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_game_id is null or btrim(p_game_id) = '' then
    raise exception 'game_id is required';
  end if;

  if p_date_key is null or btrim(p_date_key) = '' then
    raise exception 'date_key is required';
  end if;

  if p_date_key <> v_current_date_key then
    raise exception 'Daily challenge is only valid for today';
  end if;

  if p_seed is distinct from v_expected_seed then
    raise exception 'Invalid daily challenge seed';
  end if;

  insert into public.daily_scores (
    user_id,
    game_id,
    date_key,
    seed,
    score,
    replay_code,
    summary_json
  )
  values (
    v_user_id,
    p_game_id,
    p_date_key,
    p_seed,
    greatest(coalesce(p_score, 0), 0),
    p_replay_code,
    case
      when p_summary_json is null or btrim(p_summary_json) = '' then null
      else p_summary_json::jsonb
    end
  )
  on conflict (user_id, game_id, date_key) do nothing
  returning score into v_inserted_score;

  if v_inserted_score is null then
    raise exception 'Daily attempt already used';
  end if;

  return v_inserted_score;
end;
$$;

create or replace function public.get_daily_leaderboard(
  p_game_id text,
  p_date_key text default null,
  p_limit integer default 20
)
returns table (
  user_id uuid,
  score integer,
  nickname text,
  avatar_url text,
  rank bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with target_day as (
    select coalesce(p_date_key, to_char(timezone('Asia/Seoul', now()), 'YYYY-MM-DD')) as date_key
  ),
  ranked as (
    select
      ds.user_id,
      ds.score,
      ds.created_at,
      rank() over (order by ds.score desc) as rank
    from public.daily_scores ds
    cross join target_day td
    where ds.game_id = p_game_id
      and ds.date_key = td.date_key
  )
  select
    r.user_id,
    r.score,
    coalesce(
      nullif(btrim(p.nickname), ''),
      'Player ' || upper(substr(r.user_id::text, 1, 6))
    ) as nickname,
    p.avatar_url,
    r.rank
  from ranked r
  left join public.profiles p
    on p.id = r.user_id
  order by r.rank asc, r.created_at asc, r.user_id asc
  limit greatest(coalesce(p_limit, 20), 1);
$$;

create or replace function public.get_my_daily_rank(
  p_game_id text,
  p_date_key text default null
)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  with target_day as (
    select coalesce(p_date_key, to_char(timezone('Asia/Seoul', now()), 'YYYY-MM-DD')) as date_key
  ),
  ranked as (
    select
      ds.user_id,
      rank() over (order by ds.score desc) as rank
    from public.daily_scores ds
    cross join target_day td
    where ds.game_id = p_game_id
      and ds.date_key = td.date_key
  )
  select ranked.rank::integer
  from ranked
  where ranked.user_id = auth.uid()
  limit 1;
$$;

create or replace function public.get_my_daily_best_score(
  p_game_id text,
  p_date_key text default null
)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  with target_day as (
    select coalesce(p_date_key, to_char(timezone('Asia/Seoul', now()), 'YYYY-MM-DD')) as date_key
  )
  select ds.score
  from public.daily_scores ds
  cross join target_day td
  where ds.user_id = auth.uid()
    and ds.game_id = p_game_id
    and ds.date_key = td.date_key
  limit 1;
$$;

create or replace function public.get_my_weekly_season_summary(p_game_id text)
returns table (
  week_key text,
  participant_count integer,
  rank integer,
  score integer,
  tier text
)
language sql
stable
security definer
set search_path = public
as $$
  with current_week as (
    select to_char(timezone('Asia/Seoul', now()), 'IYYY-IW') as week_key
  ),
  ranked as (
    select
      ws.user_id,
      ws.score,
      rank() over (order by ws.score desc) as rank,
      count(*) over () as participant_count
    from public.weekly_scores ws
    cross join current_week cw
    where ws.game_id = p_game_id
      and ws.week_key = cw.week_key
  )
  select
    cw.week_key,
    r.participant_count::integer,
    r.rank::integer,
    r.score,
    case
      when r.participant_count <= 0 then 'bronze'
      when (r.rank::numeric / r.participant_count::numeric) <= 0.01 then 'diamond'
      when (r.rank::numeric / r.participant_count::numeric) <= 0.05 then 'platinum'
      when (r.rank::numeric / r.participant_count::numeric) <= 0.20 then 'gold'
      when (r.rank::numeric / r.participant_count::numeric) <= 0.50 then 'silver'
      else 'bronze'
    end as tier
  from current_week cw
  left join ranked r
    on r.user_id = auth.uid();
$$;

revoke all on function public.get_daily_challenge_seed(text, text) from public;
revoke all on function public.get_daily_challenge(text) from public;
revoke all on function public.submit_daily_score(text, text, integer, integer, text, text) from public;
revoke all on function public.get_daily_leaderboard(text, text, integer) from public;
revoke all on function public.get_my_daily_rank(text, text) from public;
revoke all on function public.get_my_daily_best_score(text, text) from public;
revoke all on function public.get_my_weekly_season_summary(text) from public;

grant execute on function public.get_daily_challenge(text) to anon;
grant execute on function public.get_daily_challenge(text) to authenticated;
grant execute on function public.submit_daily_score(text, text, integer, integer, text, text) to authenticated;
grant execute on function public.get_daily_leaderboard(text, text, integer) to anon;
grant execute on function public.get_daily_leaderboard(text, text, integer) to authenticated;
grant execute on function public.get_my_daily_rank(text, text) to authenticated;
grant execute on function public.get_my_daily_best_score(text, text) to authenticated;
grant execute on function public.get_my_weekly_season_summary(text) to authenticated;

notify pgrst, 'reload schema';
