create table if not exists public.daily_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  game_id text not null,
  date_key text not null,
  seed integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, game_id, date_key)
);

create index if not exists daily_attempts_game_date_idx
  on public.daily_attempts (game_id, date_key, user_id);

alter table public.daily_attempts enable row level security;

drop trigger if exists daily_attempts_set_updated_at on public.daily_attempts;
create trigger daily_attempts_set_updated_at
before update on public.daily_attempts
for each row
execute function public.set_updated_at();

drop policy if exists daily_attempts_select_own on public.daily_attempts;
create policy daily_attempts_select_own
on public.daily_attempts
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists daily_attempts_insert_own on public.daily_attempts;
create policy daily_attempts_insert_own
on public.daily_attempts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists daily_attempts_update_own on public.daily_attempts;
create policy daily_attempts_update_own
on public.daily_attempts
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists daily_attempts_delete_own on public.daily_attempts;
create policy daily_attempts_delete_own
on public.daily_attempts
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.get_daily_challenge(p_game_id text)
returns table (
  date_key text,
  seed integer,
  has_used_entry boolean,
  my_score integer
)
language sql
stable
security definer
set search_path = public
as $$
  with current_day as (
    select to_char(timezone('Asia/Seoul', now()), 'YYYY-MM-DD') as date_key
  ),
  my_attempt as (
    select 1
    from public.daily_attempts da
    cross join current_day cd
    where da.user_id = auth.uid()
      and da.game_id = p_game_id
      and da.date_key = cd.date_key
    limit 1
  ),
  my_entry as (
    select ds.score
    from public.daily_scores ds
    cross join current_day cd
    where ds.user_id = auth.uid()
      and ds.game_id = p_game_id
      and ds.date_key = cd.date_key
    limit 1
  )
  select
    cd.date_key,
    public.get_daily_challenge_seed(p_game_id, cd.date_key) as seed,
    exists(select 1 from my_attempt) or exists(select 1 from my_entry) as has_used_entry,
    (select score from my_entry limit 1) as my_score
  from current_day cd;
$$;

create or replace function public.claim_daily_challenge_entry(p_game_id text)
returns table (
  date_key text,
  seed integer,
  has_used_entry boolean,
  my_score integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_date_key text := to_char(timezone('Asia/Seoul', now()), 'YYYY-MM-DD');
  v_seed integer := public.get_daily_challenge_seed(p_game_id, v_date_key);
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_game_id is null or btrim(p_game_id) = '' then
    raise exception 'game_id is required';
  end if;

  if exists (
    select 1
    from public.daily_attempts da
    where da.user_id = v_user_id
      and da.game_id = p_game_id
      and da.date_key = v_date_key
  ) or exists (
    select 1
    from public.daily_scores ds
    where ds.user_id = v_user_id
      and ds.game_id = p_game_id
      and ds.date_key = v_date_key
  ) then
    raise exception 'Daily challenge already used';
  end if;

  insert into public.daily_attempts (user_id, game_id, date_key, seed)
  values (v_user_id, p_game_id, v_date_key, v_seed);

  return query
  select
    v_date_key,
    v_seed,
    true,
    null::integer;
end;
$$;

create or replace function public.submit_daily_score(
  p_game_id text,
  p_date_key text,
  p_seed integer,
  p_score integer,
  p_replay_code text default null,
  p_summary_json text default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_current_date_key text := to_char(timezone('Asia/Seoul', now()), 'YYYY-MM-DD');
  v_expected_seed integer := public.get_daily_challenge_seed(p_game_id, p_date_key);
  v_inserted_score integer;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_game_id is null or btrim(p_game_id) = '' then
    raise exception 'game_id is required';
  end if;

  if p_date_key is null or btrim(p_date_key) = '' then
    raise exception 'date_key is required';
  end if;

  if p_date_key <> v_current_date_key then
    raise exception 'Daily challenge is only valid for today';
  end if;

  if p_seed is distinct from v_expected_seed then
    raise exception 'Invalid daily challenge seed';
  end if;

  if not exists (
    select 1
    from public.daily_attempts da
    where da.user_id = v_user_id
      and da.game_id = p_game_id
      and da.date_key = p_date_key
  ) then
    raise exception 'Daily challenge entry not claimed';
  end if;

  insert into public.daily_scores (
    user_id,
    game_id,
    date_key,
    seed,
    score,
    replay_code,
    summary_json
  )
  values (
    v_user_id,
    p_game_id,
    p_date_key,
    p_seed,
    greatest(coalesce(p_score, 0), 0),
    p_replay_code,
    case
      when p_summary_json is null or btrim(p_summary_json) = '' then null
      else p_summary_json::jsonb
    end
  )
  on conflict (user_id, game_id, date_key)
  do update
  set
    seed = excluded.seed,
    score = excluded.score,
    replay_code = excluded.replay_code,
    summary_json = excluded.summary_json,
    updated_at = timezone('utc', now())
  returning score into v_inserted_score;

  return v_inserted_score;
end;
$$;

revoke all on function public.get_daily_challenge(text) from public;
revoke all on function public.claim_daily_challenge_entry(text) from public;
revoke all on function public.submit_daily_score(text, text, integer, integer, text, text) from public;

grant execute on function public.get_daily_challenge(text) to anon;
grant execute on function public.get_daily_challenge(text) to authenticated;
grant execute on function public.claim_daily_challenge_entry(text) to authenticated;
grant execute on function public.submit_daily_score(text, text, integer, integer, text, text) to authenticated;

notify pgrst, 'reload schema';
