-- Keep the legacy Hexor app working with the existing all-time ranking RPCs,
-- and add explicit weekly/all-time APIs for the next release.
--
-- Why a separate weekly table?
-- The currently deployed app only syncs when the player's all-time local best
-- beats the server all-time best. That means it cannot reliably populate a
-- weekly board. Changing submit_score now would break ranking continuity for
-- deployed clients. So weekly data must use a new write path.

create table if not exists public.weekly_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  game_id text not null,
  week_key text not null,
  score integer not null default 0 check (score >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, game_id, week_key)
);

create index if not exists weekly_scores_game_week_score_idx
  on public.weekly_scores (game_id, week_key, score desc, updated_at asc);

create index if not exists weekly_scores_user_game_idx
  on public.weekly_scores (user_id, game_id, week_key);

alter table public.weekly_scores enable row level security;

drop trigger if exists weekly_scores_set_updated_at on public.weekly_scores;
create trigger weekly_scores_set_updated_at
before update on public.weekly_scores
for each row
execute function public.set_updated_at();

drop policy if exists weekly_scores_select_own on public.weekly_scores;
create policy weekly_scores_select_own
on public.weekly_scores
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists weekly_scores_insert_own on public.weekly_scores;
create policy weekly_scores_insert_own
on public.weekly_scores
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists weekly_scores_update_own on public.weekly_scores;
create policy weekly_scores_update_own
on public.weekly_scores
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists weekly_scores_delete_own on public.weekly_scores;
create policy weekly_scores_delete_own
on public.weekly_scores
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.submit_weekly_score(p_game_id text, p_score integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_best_score integer;
  v_next_score integer := greatest(coalesce(p_score, 0), 0);
  v_week_key text := to_char(timezone('Asia/Seoul', now()), 'IYYY-IW');
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_game_id is null or btrim(p_game_id) = '' then
    raise exception 'game_id is required';
  end if;

  insert into public.weekly_scores (user_id, game_id, week_key, score)
  values (v_user_id, p_game_id, v_week_key, v_next_score)
  on conflict (user_id, game_id, week_key)
  do update
  set
    score = greatest(public.weekly_scores.score, excluded.score),
    updated_at = timezone('utc', now())
  returning score into v_best_score;

  return v_best_score;
end;
$$;

create or replace function public.get_weekly_leaderboard(
  p_game_id text,
  p_limit integer default 20
)
returns table (
  user_id uuid,
  score integer,
  nickname text,
  avatar_url text,
  rank bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with current_week as (
    select to_char(timezone('Asia/Seoul', now()), 'IYYY-IW') as week_key
  ),
  ranked as (
    select
      ws.user_id,
      ws.score,
      ws.updated_at,
      rank() over (order by ws.score desc) as rank
    from public.weekly_scores ws
    cross join current_week cw
    where ws.game_id = p_game_id
      and ws.week_key = cw.week_key
  )
  select
    r.user_id,
    r.score,
    coalesce(
      nullif(btrim(p.nickname), ''),
      'Player ' || upper(substr(r.user_id::text, 1, 6))
    ) as nickname,
    p.avatar_url,
    r.rank
  from ranked r
  left join public.profiles p
    on p.id = r.user_id
  order by r.rank asc, r.updated_at asc, r.user_id asc
  limit greatest(coalesce(p_limit, 20), 1);
$$;

create or replace function public.get_my_weekly_rank(p_game_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  with current_week as (
    select to_char(timezone('Asia/Seoul', now()), 'IYYY-IW') as week_key
  ),
  ranked as (
    select
      ws.user_id,
      rank() over (order by ws.score desc) as rank
    from public.weekly_scores ws
    cross join current_week cw
    where ws.game_id = p_game_id
      and ws.week_key = cw.week_key
  )
  select ranked.rank::integer
  from ranked
  where ranked.user_id = auth.uid()
  limit 1;
$$;

create or replace function public.get_my_weekly_best_score(p_game_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  with current_week as (
    select to_char(timezone('Asia/Seoul', now()), 'IYYY-IW') as week_key
  )
  select ws.score
  from public.weekly_scores ws
  cross join current_week cw
  where ws.user_id = auth.uid()
    and ws.game_id = p_game_id
    and ws.week_key = cw.week_key
  limit 1;
$$;

create or replace function public.get_all_time_leaderboard(
  p_game_id text,
  p_limit integer default 20
)
returns table (
  user_id uuid,
  score integer,
  nickname text,
  avatar_url text,
  rank bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select *
  from public.get_leaderboard(p_game_id, p_limit);
$$;

create or replace function public.get_my_all_time_rank(p_game_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select public.get_my_rank(p_game_id);
$$;

create or replace function public.get_my_all_time_best_score(p_game_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select public.get_my_best_score(p_game_id);
$$;

revoke all on function public.submit_weekly_score(text, integer) from public;
revoke all on function public.get_weekly_leaderboard(text, integer) from public;
revoke all on function public.get_my_weekly_rank(text) from public;
revoke all on function public.get_my_weekly_best_score(text) from public;
revoke all on function public.get_all_time_leaderboard(text, integer) from public;
revoke all on function public.get_my_all_time_rank(text) from public;
revoke all on function public.get_my_all_time_best_score(text) from public;

grant execute on function public.submit_weekly_score(text, integer) to authenticated;
grant execute on function public.get_weekly_leaderboard(text, integer) to anon;
grant execute on function public.get_weekly_leaderboard(text, integer) to authenticated;
grant execute on function public.get_my_weekly_rank(text) to authenticated;
grant execute on function public.get_my_weekly_best_score(text) to authenticated;
grant execute on function public.get_all_time_leaderboard(text, integer) to anon;
grant execute on function public.get_all_time_leaderboard(text, integer) to authenticated;
grant execute on function public.get_my_all_time_rank(text) to authenticated;
grant execute on function public.get_my_all_time_best_score(text) to authenticated;

notify pgrst, 'reload schema';
