create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  nickname text,
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles
  add column if not exists nickname text,
  add column if not exists avatar_url text,
  add column if not exists created_at timestamptz default timezone('utc', now()),
  add column if not exists updated_at timestamptz default timezone('utc', now());

update public.profiles
set
  created_at = coalesce(created_at, timezone('utc', now())),
  updated_at = coalesce(updated_at, timezone('utc', now()))
where created_at is null
   or updated_at is null;

alter table public.profiles
  alter column created_at set default timezone('utc', now()),
  alter column updated_at set default timezone('utc', now()),
  alter column created_at set not null,
  alter column updated_at set not null;

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  game_id text not null,
  score integer not null default 0 check (score >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.scores
  add column if not exists created_at timestamptz default timezone('utc', now()),
  add column if not exists updated_at timestamptz default timezone('utc', now());

update public.scores
set
  created_at = coalesce(created_at, timezone('utc', now())),
  updated_at = coalesce(updated_at, timezone('utc', now()))
where created_at is null
   or updated_at is null;

alter table public.scores
  alter column created_at set default timezone('utc', now()),
  alter column updated_at set default timezone('utc', now()),
  alter column created_at set not null,
  alter column updated_at set not null;

create index if not exists scores_game_score_idx
  on public.scores (game_id, score desc, updated_at asc);

create index if not exists scores_user_game_idx
  on public.scores (user_id, game_id);

alter table public.profiles enable row level security;
alter table public.scores enable row level security;

insert into public.profiles (id)
select u.id
from auth.users u
left join public.profiles p on p.id = u.id
where p.id is null;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists scores_set_updated_at on public.scores;
create trigger scores_set_updated_at
before update on public.scores
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists scores_select_own on public.scores;
create policy scores_select_own
on public.scores
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists scores_insert_own on public.scores;
create policy scores_insert_own
on public.scores
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists scores_update_own on public.scores;
create policy scores_update_own
on public.scores
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists scores_delete_own on public.scores;
create policy scores_delete_own
on public.scores
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.submit_score(p_game_id text, p_score integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_row_id bigint;
  v_best_score integer;
  v_next_score integer := greatest(coalesce(p_score, 0), 0);
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_game_id is null or btrim(p_game_id) = '' then
    raise exception 'game_id is required';
  end if;

  select s.id, s.score
  into v_row_id, v_best_score
  from public.scores s
  where s.user_id = v_user_id
    and s.game_id = p_game_id
  order by s.score desc, s.updated_at desc, s.id desc
  limit 1
  for update;

  if v_row_id is null then
    insert into public.scores (user_id, game_id, score)
    values (v_user_id, p_game_id, v_next_score)
    returning id, score into v_row_id, v_best_score;
  else
    update public.scores
    set score = greatest(score, v_next_score)
    where id = v_row_id
    returning score into v_best_score;

    delete from public.scores
    where user_id = v_user_id
      and game_id = p_game_id
      and id <> v_row_id;
  end if;

  return v_best_score;
end;
$$;

create or replace function public.get_my_best_score(p_game_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  with best_scores as (
    select distinct on (s.user_id)
      s.user_id,
      s.score,
      s.updated_at
    from public.scores s
    where s.game_id = p_game_id
    order by s.user_id, s.score desc, s.updated_at asc, s.id asc
  )
  select bs.score
  from best_scores bs
  where bs.user_id = auth.uid()
  limit 1;
$$;

create or replace function public.get_my_rank(p_game_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  with best_scores as (
    select distinct on (s.user_id)
      s.user_id,
      s.score,
      s.updated_at
    from public.scores s
    where s.game_id = p_game_id
    order by s.user_id, s.score desc, s.updated_at asc, s.id asc
  ),
  ranked as (
    select
      bs.user_id,
      rank() over (order by bs.score desc) as rank
    from best_scores bs
  )
  select ranked.rank::integer
  from ranked
  where ranked.user_id = auth.uid()
  limit 1;
$$;

create or replace function public.get_leaderboard(
  p_game_id text,
  p_limit integer default 50
)
returns table (
  user_id uuid,
  score integer,
  nickname text,
  avatar_url text,
  rank bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with best_scores as (
    select distinct on (s.user_id)
      s.user_id,
      s.score,
      s.updated_at
    from public.scores s
    where s.game_id = p_game_id
    order by s.user_id, s.score desc, s.updated_at asc, s.id asc
  ),
  ranked as (
    select
      bs.user_id,
      bs.score,
      bs.updated_at,
      rank() over (order by bs.score desc) as rank
    from best_scores bs
  )
  select
    r.user_id,
    r.score,
    coalesce(
      nullif(btrim(p.nickname), ''),
      'Player ' || upper(substr(r.user_id::text, 1, 6))
    ) as nickname,
    p.avatar_url,
    r.rank
  from ranked r
  left join public.profiles p
    on p.id = r.user_id
  order by r.rank asc, r.updated_at asc, r.user_id asc
  limit greatest(coalesce(p_limit, 50), 1);
$$;

create or replace function public.is_nickname_available(p_nickname text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not exists (
    select 1
    from public.profiles p
    where p.nickname = p_nickname
      and p.id <> auth.uid()
  );
$$;

create or replace function public.delete_my_account_data()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  delete from public.scores
  where user_id = v_user_id
    and game_id = 'hexor';
end;
$$;

grant execute on function public.submit_score(text, integer) to authenticated;
grant execute on function public.get_my_best_score(text) to authenticated;
grant execute on function public.get_my_rank(text) to authenticated;
grant execute on function public.get_leaderboard(text, integer) to authenticated;
grant execute on function public.is_nickname_available(text) to authenticated;
grant execute on function public.delete_my_account_data() to authenticated;
